
# Metodo del Gradiente Coniugato con SciPy

In questo notebook esploriamo l'uso della funzione `cg` di SciPy per risolvere un sistema lineare mediante il metodo del gradiente coniugato. In particolare, analizziamo l'uso della funzione *callback* per memorizzare le iterazioni intermedie.


In [1]:
# import
import numpy as np
from scipy.sparse.linalg import cg


## Definizione della matrice e dei parametri

In [2]:
# Dimensione della matrice
n = 7

# Costruzione della matrice A
A = -3 * np.diag(np.ones(n-1), 1) + np.diag(np.ones(n-2), 2)
A = 9 * np.diag(np.ones(n)) + A + A.T

# Termine noto
b = np.array([7, 4, 5, 5, 5, 4, 7])

# Guess iniziale
x0 = np.zeros(n)

# Tolleranza e numero massimo di iterazioni
rtoll = 1e-6
nmax = 1000

# Visualizzazione della matrice A
print("Matrice A:")
print(A)


Matrice A:
[[ 9. -3.  1.  0.  0.  0.  0.]
 [-3.  9. -3.  1.  0.  0.  0.]
 [ 1. -3.  9. -3.  1.  0.  0.]
 [ 0.  1. -3.  9. -3.  1.  0.]
 [ 0.  0.  1. -3.  9. -3.  1.]
 [ 0.  0.  0.  1. -3.  9. -3.]
 [ 0.  0.  0.  0.  1. -3.  9.]]


## Risoluzione del sistema con `cg`

In [3]:
# Esecuzione del metodo del gradiente coniugato
x = cg(A, b, x0, rtol=rtoll, maxiter=nmax)
print(x)

(array([1., 1., 1., 1., 1., 1., 1.]), 0)


Mi restituisce due output: l'ultima iterazione e un marker: 0 converge, >0 non converge. Qui sotto trovate la documentazione

https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.cg.html

In [4]:
# Stampo i due output del metodo del gradiente coniugato
x, info = cg(A, b, x0, rtol=rtoll, maxiter=nmax)
# Output
print("Soluzione finale:")
print(x)
print("Info:")
print(info)

# Un altro modo per stampare solo il primo output è 
x = cg(A, b, x0, rtol=1e-6, maxiter=1000)[0]
# Output
print("\nSoluzione finale:")
print(x)


Soluzione finale:
[1. 1. 1. 1. 1. 1. 1.]
Info:
0

Soluzione finale:
[1. 1. 1. 1. 1. 1. 1.]


Usando la prima sintassi abbiamo due output e sfruttiamo il concetto di tupla, Mentre nella seconda sinstassi invece richiediamo solo il primo output. Quest'ultima sintassi, se ci pensate bene, può essere usata anche per altre funzioni dove abbiamo più output. Un esempio molto semplice, che riportiamo qui sotto, riguarda alla funzione $\texttt{shape}$. 

In [5]:
# stampo la dimensione di A
print(A.shape)
# oppure posso farlo in questa maniera
print(np.shape(A))

# ora voglio calcolare il numero di righe
# quello che abbiamo visto nelle prime lezioni
print(A.shape[0])
# quello usando la scrittura definita sopra
print(np.shape(A)[0])
# osserviamo che è la stessa cosa

(7, 7)
(7, 7)
7
7


## Uso della funzione `callback`

In [6]:

# Lista per salvare le iterazioni
xcg = [x0]

# Callback per salvare ogni iterazione
x_finale, info = cg(A, b, x0, rtol=rtoll, maxiter=nmax, callback=lambda xk: xcg.append(xk+0.0))

# Output
print("Soluzione finale:")
print(x_finale)
print("Numero di iterazioni: %d" %(len(xcg)-1))


Soluzione finale:
[1. 1. 1. 1. 1. 1. 1.]
Numero di iterazioni: 4


Possiamo osservare come $\texttt{x\_finale}$ sarà sempre l'iterata finale, mentre con $\texttt{callback}$ creiamo una lista $\texttt{xcg}$ che è la lista di tutte le iterate, compresa la guess iniziale e che possiamo sfruttare per sapere il numero di iterazioni fatte.